---
name: Python Setup
description: Setup Python for the project

runs:
  using: composite
  steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r scripts/requirements.txt
