---
name: Go Setup
description: Setup Go for the project

runs:
  using: composite
  steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install Go dependencies
        shell: bash
        run: go mod download
