---
name: Node Setup
description: Setup Node.js for the project

runs:
  using: composite
  steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"
          cache: "pnpm"
