---
name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
